---
- name: add group
  group: 
    name={{ item.name }}
    gid={{ item.gid }}
    state=present
  with_items: "{{ group }}"

- name: add user
  user:
    name={{ item.name }}
    comment={{ item.comment }}
    uid={{ item.uid }}
    groups={{ item.groups }}
  with_items: "{{ user }}"

- name: add keys
  authorized_key:
    user={{ item.user }} 
    key="{{ lookup('file', '{{ item.key }}') }}"
  with_items: "{{ authorized_keys }}"
 
- name: make sure we have a wheel group
  group:
    name: wheel
    state: present

- name: ensure /etc/sudoers.d directory is present
  file: path=/etc/sudoers.d state=directory

- name: ensure file in /etc/sudoers.d/ is present
  file: 
    path={{ item.path }} 
    state=touch 
    mode=044 
    owner=root 
    group=root
  with_items: "{{ sudopath }}" 

- name: add sudo permissions to /etc/sudoers.d/
  lineinfile:
    dest={{ item.path }}
    state=present
    create=yes
    line={{ item.line }}
    regexp={{ item.regexp }}
  with_items: "{{ privileges }}"

- name: manging sudoers file
  lineinfile: 
    "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel        ALL=(ALL)       NOPASSWD: ALL'"
