---
#ntp
ntp_servers:
- 0.centos.pool.ntp.org
- 1.centos.pool.ntp.org
- 2.centos.pool.ntp.org

#User
group:
  - name: willi.fehler
    gid: 1000
  - name: toni.fehler
    gid: 1001
user:
  - name: willi.fehler
    comment: "Willi Fehler"
    uid: 1000
    groups: "willi.fehler,wheel"
  - name: toni.fehler
    comment: "Toni Fehler"
    uid: 1001
    groups: "toni.fehler,wheel"
authorized_key:
  - user: willi.fehler
    key: "{{ lookup('file', 'willifehler.pub') }}"  
  - user: toni.fehler
    key: "{{ lookup('file', 'tonifehler.pub') }}"
sudofile:
  - path: /etc/sudoers.d/toni.fehler
  - path: /etc/sudoers.d/willi.fehler
sudopermission:
  - path: /etc/sudoers.d/toni.fehler
    line: "ALL = NOPASSWD: /bin/systemctl restart ntpd"
    regexp: "toni.fehler" 
 
#MySQL
server_id: 21
mysql_databases:
  - name: willifehler
  - name: tonifehler
mysql_users:
  - name: willifehler
    password: test
    priv: 'willifehler.*:ALL'
    host: '%'

#Apache
apache_documentroot: 
  - { name: "willi-fehler", directory: "/var/www/willi-fehler.de" } 
  - { name: "toni-fehler", directory: "/var/www/toni-fehler.de" } 
apache_vhosts: 
  willi-fehler.de:
    - ServerAdmin willi@willi-fehler.de
    - DocumentRoot "/var/www/willi-fehler.de"
    - ServerName willi-fehler.de
    - ServerAlias *.willi-fehler.de 
    - ErrorLog /var/log/httpd/willi-fehler.de-error.log
    - CustomLog /var/log/httpd/willi-fehler.de-access.log combined
  toni-fehler.de:
    - ServerAdmin toni@toni-fehler.de
    - DocumentRoot "/var/www/toni-fehler.de"
    - ServerName toni-fehler.de
    - ServerAlias *.toni-fehler.de
    - ErrorLog /var/log/httpd/toni-fehler.de-error.log
    - CustomLog /var/log/httpd/toni-fehler.de-access.log combined
apache_vhosts_ssl:
  willi-fehler.de:
    - ServerAdmin willi@willi-fehler.de
    - DocumentRoot "/var/www/willi-fehler.de"
    - ServerName willi-fehler.de
    - ServerAlias *.willi-fehler.de
    - ErrorLog /var/log/httpd/willi-fehler.de-error.log
    - CustomLog /var/log/httpd/willi-fehler.de-access.log combined
    - SSLEngine on
    - SSLCertificateFile /etc/pki/tls/certs/localhost.crt
    - SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
  toni-fehler.de:
    - ServerAdmin toni@toni-fehler.de
    - DocumentRoot "/var/www/toni-fehler.de"
    - ServerName toni-fehler.de
    - ServerAlias *.toni-fehler.de
    - ErrorLog /var/log/httpd/toni-fehler.de-error.log
    - CustomLog /var/log/httpd/toni-fehler.de-access.log combined
    - SSLEngine on
    - SSLCertificateFile /etc/pki/tls/certs/localhost.crt
    - SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
