---
#ntp
ntp_servers:
- 3.de.pool.ntp.org
- 4.de.pool.ntp.org
#mysql
server_id: 21
#httpd
apache_vhosts: 
  willi-fehler.de:
    - DocumentRoot /var/www/willi-fehler 
    - ServerName willi-fehler.de
    - ServerAlias *.willi-fehler.de 
    - ErrorLog /var/log/httpd/willi-fehler.de-error.log
    - CustomLog /var/log/httpd/willi-fehler.de-access.log combined
  toni-fehler.de:
    - DocumentRoot /var/www/toni-fehler
    - ServerName toni-fehler.de
    - ServerAlias *.toni-fehler.de
    - ErrorLog /var/log/httpd/toni-fehler.de-error.log
    - CustomLog /var/log/httpd/toni-fehler.de-access.log combined
