---
ntp_servers:
- 3.de.pool.ntp.org
- 4.de.pool.ntp.org
server_id: 21
apache_vhosts_filename: "willi-fehler.de.conf"
apache_vhosts: 
  - servername: "www.willi-fehler.de"
  - servername: "www.toni-fehler.de"
