---
- name: install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
    - mariadb-server
    - MySQL-python

- name: configure useful swappiness setting
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: start MariaDB service
  service: name=mariadb state=started enabled=yes

- name: generate new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_pass

- name: remove anonymous users
  mysql_user: name="" state=absent
  when: mysql_new_root_pass.changed
   
- name: remove test database
  mysql_db: name=test state=absent
  when: mysql_new_root_pass.changed
 
- name: output new root password
  debug: msg="new root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed

- name: update root password
  mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
  with_items:
    - "{{ansible_hostname}}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_new_root_pass.changed

- name: create root .my.cnf
  template: src=templates/root_my.cnf.j2 dest=/root/.my.cnf
  when: mysql_new_root_pass.changed

- name: create MySQL configuration file
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mariadb
  register: mysql_innodb_log_file_size
  
- name: Ensure MariaDB is started after changing innodb_log_file_size
  service: "name=mariadb state=stopped"
  when: mysql_innodb_log_file_size.changed

- name: Delete innodb log files
  file: path=/var/lib/mysql/{{item}} state=absent
  with_items:
          - "ib_logfile0"
          - "ib_logfile1"
  when: mysql_innodb_log_file_size.changed
  
- name: Ensure MariaDB is started after changing innodb_log_file_size
  service: "name=mariadb state=started"
  when: mysql_innodb_log_file_size.changed

- name: create MySQL logrotate
  template: src=templates/mariadb.j2 dest=/etc/logrotate.d/mariadb
 
- name: create MySQL databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: "{{ mysql_databases }}"

- name: create MySQL database user
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv  }}"
    host: "{{ item.host }}"
    state: present
  with_items: "{{ mysql_users }}"
