---
- name: install certbot package
  yum: name=python-certbot-apache state=installed

- name: chcek if we've generated a cert already
  stat: path=/etc/letsencrypt/live/{{ letsencrypt_domain_flags }}/fullchain.pem
  register: cert_stats

- name: generate certs (first time)
  shell: "certbot certonly --apache {{ letsencrypt_domain_flags | join(' ') }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"
  when: cert_stats.stat.exists == False

- cron:
    name: "renew certificates"
    weekday: "1"
    minute: "30"
    hour: "2"
    job: "/bin/certbot renew"
