---
- name: install certbot package
  yum: name=python-certbot-apache state=installed

- name: chcek if we've generated a certificate already
  stat: path=/etc/letsencrypt/live/{{ letsencrypt_domain_flags }}/fullchain.pem
  register: cert_stats

- name: generate certificate
  shell: "certbot certonly --pre-hook 'systemctl stop httpd' --standalone {{ letsencrypt_domain_flags | join(' ') }} --email {{ letsencrypt_email}} --non-interactive --agree-tos --post-hook 'systemctl start httpd'"
  when: cert_stats.stat.exists == False

- name: create cronjob automatically renew certificates
- cron:
    name: "renew certificates"
    weekday: "1"
    minute: "30"
    hour: "2"
    job: "/bin/certbot renew"
