---
- name: install the latest version of Apache
  yum: name={{ item }}  state=latest
  with_items:
    - httpd
    - mod_ssl

- name: start httpd
  service: name=httpd state=started enabled=yes

- name: create Apache DocumentRoot
  file: dest="{{ item.directory }}" 
        mode=755 
        state=directory 
  with_items: "{{ apache_documentroot }}"

- name: create httpd configuration file
  template: src=templates/httpd.conf.j2 dest="/etc/httpd/conf/httpd.conf"
  notify:
    - restart httpd

- name: create ssl configuration file
  template: src=templates/ssl.conf.j2 dest="/etc/httpd/conf.d/ssl.conf"
  notify:
    - restart httpd

- name: create hostname configuration file
  template: src=templates/hostname.conf.j2 dest="/etc/httpd/conf.d/hostname.conf"
  notify:
    - restart httpd

- name: create security configuration file
  template: src=templates/security.conf.j2 dest="/etc/httpd/conf.d/security.conf"
  notify:
    - restart httpd

- name: create vhost configuration file
  template: src=templates/vhost.j2 dest="/etc/httpd/conf.d/{{ item }}.conf"
  with_items: "{{ apache_vhosts.keys() }}"
  notify:
    - restart httpd
