---
- name: manage selinux
  selinux: state=disabled

- name: disable tcp_timestamps
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: 0
    state: present

- name: install epel repository
  yum: name=epel-release state=latest

- name: install common packages
  yum: name={{ item }} state=latest
  with_items:
    - htop
    - iftop
    - iotop
    - glances
    - vim
    - git
    - tree
    - yum-utils

- name: ensure ntp is at the latest version
  yum: name=ntp state=latest

- name: write the ntp config file
  template: src=templates/ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp

- name: ensure ntp is running
  service: name=ntpd state=started
