---
- name: install the ius.io rpm from a remote repo
  yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=present

- name: install the latest php from ius.io
  yum: name={{ item }} enablerepo=ius state=latest
  with_items:
    - mod_php70u
    - php70u-cli
    - php70u-gd
    - php70u-mbstring
    - php70u-mcrypt
    - php70u-mysqlnd
  notify:
    - restart httpd

- name: create php.ini
  template: src=templates/php.ini.j2 dest=/etc/php.ini
  notify:
    - restart httpd

- name: create a info.php file
  copy:
    content: |
      <?php
      phpinfo();
      ?>
    dest: /var/www/html/info.php
    force: no
    group: apache
    owner: apache
    mode: 0644
