---
- name: install LAMP configuration on localhost
  hosts: localhost
  roles:
    - roles/user
    - roles/common
    - roles/certbot
    - roles/httpd
    - roles/php
    - roles/mysql
    - roles/docker
