---
- name: install LAMP configuration on localhost
  hosts: localhost
  roles:
    - roles/user
    - roles/common
    - roles/certbot
    - roles/httpd
    - roles/php
    - roles/mysql
    - roles/docker

- name: start container
  hosts: localhost
  tasks:
    - name: start owncloud container
      docker_container:
        image: centos
        command: sleep infinity
        name: owncloud
        hostname: owncloud
        state: started
        ports:
          - "81:80"
