---
- name: install LAMP configuration on localhost
  hosts: localhost
  roles:
    - roles/ssh
    - roles/user
    - roles/common
    - roles/certbot
    - roles/httpd
    - roles/php
    - roles/mysql
    - roles/docker

- name: nextcloud volume create
  hosts: localhost
  tasks:
    - name: nextcloud docker volume create
      command: docker volume create --name nextcloud
      ignore_errors: yes

- name: start container
  hosts: localhost
  tasks:
    - name: start nextcloud container
      docker_container:
        image: willi/nextcloud
        name: nextcloud
        hostname: nextcloud
        state: started
        ports:
          - "81:80"
        volumes:
          - nextcloud:/var/www/html
